import { test, expect, mock, afterEach } from 'bun:test';
import { Window } from 'happy-dom';
import { act } from 'react';
import { createRoot } from 'react-dom/client';
const browser = new Window({url: 'http://localhost'});
Object.assign(globalThis, {window: browser, document: browser.document, IS_REACT_ACT_ENVIRONMENT: true});
const state = {mode:'good', userHidden:false, offsetX:0, offsetY:0};
const invoke = mock(async (_command: string, _args?: unknown) => state);
const drag = mock(async () => {});
let receive: (event: any) => void;
mock.module('@tauri-apps/api/core', () => ({invoke,isTauri:()=>true}));
mock.module('@tauri-apps/api/event', () => ({listen: async (event: string, fn: any) => {if(event === 'overlay:state') receive=fn; return () => {};}}));
mock.module('@tauri-apps/api/window', () => ({getCurrentWindow: () => ({startDragging:drag,onMoved:async () => () => {}})}));
mock.module('../src/features/overlay/WebInlineCharacterOverlay', () => ({WebInlineCharacterOverlay: () => <div>pet</div>}));
const {OverlayApp} = await import('../src/overlay/OverlayApp');
const {loadStoredPositionOffset} = await import('../src/features/overlay/overlayState');
const host=document.createElement('div');document.body.append(host);
const root=createRoot(host);
afterEach(async()=>{await act(()=>root.unmount());});
test('restore legacy coordinates once; posture changes do not reposition; drag is native and unlimited',async()=>{
 window.localStorage.setItem('posture.overlay.positionOffset.v1',JSON.stringify({x:-2800,y:-1200}));
 expect(loadStoredPositionOffset()).toEqual({x:-2800,y:-1200});
 await act(async()=>root.render(<OverlayApp/>));
 expect(invoke.mock.calls.filter(x=>x[0]==='overlay_restore_position')).toEqual([['overlay_restore_position',{offsetX:-2800,offsetY:-1200}]]);
 invoke.mockClear();
 for(const mode of ['bad','paused','hidden','good']) await act(async()=>receive({payload:{...state,mode}}));
 expect(invoke).not.toHaveBeenCalled();
 await act(async()=>host.querySelector('.overlay-character')!.dispatchEvent(new browser.PointerEvent('pointerdown',{button:0,bubbles:true}) as any));
 expect(drag).toHaveBeenCalledTimes(1);
 expect(invoke).not.toHaveBeenCalled();
});
